-- Deterministic global reference data for ST-033.
-- Countries: UN Statistics Division M49 overview, retrieved 2026-07-11; 248 current country/area
-- rows with assigned ISO alpha-2 and alpha-3 codes, excluding aggregate regions.
-- Currencies: SIX Group ISO-4217 List One, published 2026-01-01 and retrieved 2026-07-11;
-- 157 unique numeric-minor-unit currencies after excluding IsFund entries, precious-metal codes,
-- testing/no-currency codes, and non-numeric minor-unit special units.
--
-- Each loop is directly idempotent: a matching canonical row is retained, a missing row is inserted,
-- and a conflicting canonical row aborts instead of being silently overwritten. is_active is a
-- platform availability flag and is deliberately excluded from conflict comparison.

SET ROLE studafy_admin;

DO $$
DECLARE
  seed record;
  existing record;
BEGIN
  FOR seed IN
    SELECT * FROM (VALUES
      ('AD', 'AND', '020', 'Andorra'),
      ('AE', 'ARE', '784', 'United Arab Emirates'),
      ('AF', 'AFG', '004', 'Afghanistan'),
      ('AG', 'ATG', '028', 'Antigua and Barbuda'),
      ('AI', 'AIA', '660', 'Anguilla'),
      ('AL', 'ALB', '008', 'Albania'),
      ('AM', 'ARM', '051', 'Armenia'),
      ('AO', 'AGO', '024', 'Angola'),
      ('AQ', 'ATA', '010', 'Antarctica'),
      ('AR', 'ARG', '032', 'Argentina'),
      ('AS', 'ASM', '016', 'American Samoa'),
      ('AT', 'AUT', '040', 'Austria'),
      ('AU', 'AUS', '036', 'Australia'),
      ('AW', 'ABW', '533', 'Aruba'),
      ('AX', 'ALA', '248', 'Åland Islands'),
      ('AZ', 'AZE', '031', 'Azerbaijan'),
      ('BA', 'BIH', '070', 'Bosnia and Herzegovina'),
      ('BB', 'BRB', '052', 'Barbados'),
      ('BD', 'BGD', '050', 'Bangladesh'),
      ('BE', 'BEL', '056', 'Belgium'),
      ('BF', 'BFA', '854', 'Burkina Faso'),
      ('BG', 'BGR', '100', 'Bulgaria'),
      ('BH', 'BHR', '048', 'Bahrain'),
      ('BI', 'BDI', '108', 'Burundi'),
      ('BJ', 'BEN', '204', 'Benin'),
      ('BL', 'BLM', '652', 'Saint Barthélemy'),
      ('BM', 'BMU', '060', 'Bermuda'),
      ('BN', 'BRN', '096', 'Brunei Darussalam'),
      ('BO', 'BOL', '068', 'Bolivia (Plurinational State of)'),
      ('BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba'),
      ('BR', 'BRA', '076', 'Brazil'),
      ('BS', 'BHS', '044', 'Bahamas'),
      ('BT', 'BTN', '064', 'Bhutan'),
      ('BV', 'BVT', '074', 'Bouvet Island'),
      ('BW', 'BWA', '072', 'Botswana'),
      ('BY', 'BLR', '112', 'Belarus'),
      ('BZ', 'BLZ', '084', 'Belize'),
      ('CA', 'CAN', '124', 'Canada'),
      ('CC', 'CCK', '166', 'Cocos (Keeling) Islands'),
      ('CD', 'COD', '180', 'Democratic Republic of the Congo'),
      ('CF', 'CAF', '140', 'Central African Republic'),
      ('CG', 'COG', '178', 'Congo'),
      ('CH', 'CHE', '756', 'Switzerland'),
      ('CI', 'CIV', '384', 'Côte d’Ivoire'),
      ('CK', 'COK', '184', 'Cook Islands'),
      ('CL', 'CHL', '152', 'Chile'),
      ('CM', 'CMR', '120', 'Cameroon'),
      ('CN', 'CHN', '156', 'China'),
      ('CO', 'COL', '170', 'Colombia'),
      ('CR', 'CRI', '188', 'Costa Rica'),
      ('CU', 'CUB', '192', 'Cuba'),
      ('CV', 'CPV', '132', 'Cabo Verde'),
      ('CW', 'CUW', '531', 'Curaçao'),
      ('CX', 'CXR', '162', 'Christmas Island'),
      ('CY', 'CYP', '196', 'Cyprus'),
      ('CZ', 'CZE', '203', 'Czechia'),
      ('DE', 'DEU', '276', 'Germany'),
      ('DJ', 'DJI', '262', 'Djibouti'),
      ('DK', 'DNK', '208', 'Denmark'),
      ('DM', 'DMA', '212', 'Dominica'),
      ('DO', 'DOM', '214', 'Dominican Republic'),
      ('DZ', 'DZA', '012', 'Algeria'),
      ('EC', 'ECU', '218', 'Ecuador'),
      ('EE', 'EST', '233', 'Estonia'),
      ('EG', 'EGY', '818', 'Egypt'),
      ('EH', 'ESH', '732', 'Western Sahara'),
      ('ER', 'ERI', '232', 'Eritrea'),
      ('ES', 'ESP', '724', 'Spain'),
      ('ET', 'ETH', '231', 'Ethiopia'),
      ('FI', 'FIN', '246', 'Finland'),
      ('FJ', 'FJI', '242', 'Fiji'),
      ('FK', 'FLK', '238', 'Falkland Islands (Malvinas)'),
      ('FM', 'FSM', '583', 'Micronesia (Federated States of)'),
      ('FO', 'FRO', '234', 'Faroe Islands'),
      ('FR', 'FRA', '250', 'France'),
      ('GA', 'GAB', '266', 'Gabon'),
      ('GB', 'GBR', '826', 'United Kingdom of Great Britain and Northern Ireland'),
      ('GD', 'GRD', '308', 'Grenada'),
      ('GE', 'GEO', '268', 'Georgia'),
      ('GF', 'GUF', '254', 'French Guiana'),
      ('GG', 'GGY', '831', 'Guernsey'),
      ('GH', 'GHA', '288', 'Ghana'),
      ('GI', 'GIB', '292', 'Gibraltar'),
      ('GL', 'GRL', '304', 'Greenland'),
      ('GM', 'GMB', '270', 'Gambia'),
      ('GN', 'GIN', '324', 'Guinea'),
      ('GP', 'GLP', '312', 'Guadeloupe'),
      ('GQ', 'GNQ', '226', 'Equatorial Guinea'),
      ('GR', 'GRC', '300', 'Greece'),
      ('GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands'),
      ('GT', 'GTM', '320', 'Guatemala'),
      ('GU', 'GUM', '316', 'Guam'),
      ('GW', 'GNB', '624', 'Guinea-Bissau'),
      ('GY', 'GUY', '328', 'Guyana'),
      ('HK', 'HKG', '344', 'China, Hong Kong Special Administrative Region'),
      ('HM', 'HMD', '334', 'Heard Island and McDonald Islands'),
      ('HN', 'HND', '340', 'Honduras'),
      ('HR', 'HRV', '191', 'Croatia'),
      ('HT', 'HTI', '332', 'Haiti'),
      ('HU', 'HUN', '348', 'Hungary'),
      ('ID', 'IDN', '360', 'Indonesia'),
      ('IE', 'IRL', '372', 'Ireland'),
      ('IL', 'ISR', '376', 'Israel'),
      ('IM', 'IMN', '833', 'Isle of Man'),
      ('IN', 'IND', '356', 'India'),
      ('IO', 'IOT', '086', 'British Indian Ocean Territory'),
      ('IQ', 'IRQ', '368', 'Iraq'),
      ('IR', 'IRN', '364', 'Iran (Islamic Republic of)'),
      ('IS', 'ISL', '352', 'Iceland'),
      ('IT', 'ITA', '380', 'Italy'),
      ('JE', 'JEY', '832', 'Jersey'),
      ('JM', 'JAM', '388', 'Jamaica'),
      ('JO', 'JOR', '400', 'Jordan'),
      ('JP', 'JPN', '392', 'Japan'),
      ('KE', 'KEN', '404', 'Kenya'),
      ('KG', 'KGZ', '417', 'Kyrgyzstan'),
      ('KH', 'KHM', '116', 'Cambodia'),
      ('KI', 'KIR', '296', 'Kiribati'),
      ('KM', 'COM', '174', 'Comoros'),
      ('KN', 'KNA', '659', 'Saint Kitts and Nevis'),
      ('KP', 'PRK', '408', 'Democratic People''s Republic of Korea'),
      ('KR', 'KOR', '410', 'Republic of Korea'),
      ('KW', 'KWT', '414', 'Kuwait'),
      ('KY', 'CYM', '136', 'Cayman Islands'),
      ('KZ', 'KAZ', '398', 'Kazakhstan'),
      ('LA', 'LAO', '418', 'Lao People''s Democratic Republic'),
      ('LB', 'LBN', '422', 'Lebanon'),
      ('LC', 'LCA', '662', 'Saint Lucia'),
      ('LI', 'LIE', '438', 'Liechtenstein'),
      ('LK', 'LKA', '144', 'Sri Lanka'),
      ('LR', 'LBR', '430', 'Liberia'),
      ('LS', 'LSO', '426', 'Lesotho'),
      ('LT', 'LTU', '440', 'Lithuania'),
      ('LU', 'LUX', '442', 'Luxembourg'),
      ('LV', 'LVA', '428', 'Latvia'),
      ('LY', 'LBY', '434', 'Libya'),
      ('MA', 'MAR', '504', 'Morocco'),
      ('MC', 'MCO', '492', 'Monaco'),
      ('MD', 'MDA', '498', 'Republic of Moldova'),
      ('ME', 'MNE', '499', 'Montenegro'),
      ('MF', 'MAF', '663', 'Saint Martin (French Part)'),
      ('MG', 'MDG', '450', 'Madagascar'),
      ('MH', 'MHL', '584', 'Marshall Islands'),
      ('MK', 'MKD', '807', 'North Macedonia'),
      ('ML', 'MLI', '466', 'Mali'),
      ('MM', 'MMR', '104', 'Myanmar'),
      ('MN', 'MNG', '496', 'Mongolia'),
      ('MO', 'MAC', '446', 'China, Macao Special Administrative Region'),
      ('MP', 'MNP', '580', 'Northern Mariana Islands'),
      ('MQ', 'MTQ', '474', 'Martinique'),
      ('MR', 'MRT', '478', 'Mauritania'),
      ('MS', 'MSR', '500', 'Montserrat'),
      ('MT', 'MLT', '470', 'Malta'),
      ('MU', 'MUS', '480', 'Mauritius'),
      ('MV', 'MDV', '462', 'Maldives'),
      ('MW', 'MWI', '454', 'Malawi'),
      ('MX', 'MEX', '484', 'Mexico'),
      ('MY', 'MYS', '458', 'Malaysia'),
      ('MZ', 'MOZ', '508', 'Mozambique'),
      ('NA', 'NAM', '516', 'Namibia'),
      ('NC', 'NCL', '540', 'New Caledonia'),
      ('NE', 'NER', '562', 'Niger'),
      ('NF', 'NFK', '574', 'Norfolk Island'),
      ('NG', 'NGA', '566', 'Nigeria'),
      ('NI', 'NIC', '558', 'Nicaragua'),
      ('NL', 'NLD', '528', 'Netherlands (Kingdom of the)'),
      ('NO', 'NOR', '578', 'Norway'),
      ('NP', 'NPL', '524', 'Nepal'),
      ('NR', 'NRU', '520', 'Nauru'),
      ('NU', 'NIU', '570', 'Niue'),
      ('NZ', 'NZL', '554', 'New Zealand'),
      ('OM', 'OMN', '512', 'Oman'),
      ('PA', 'PAN', '591', 'Panama'),
      ('PE', 'PER', '604', 'Peru'),
      ('PF', 'PYF', '258', 'French Polynesia'),
      ('PG', 'PNG', '598', 'Papua New Guinea'),
      ('PH', 'PHL', '608', 'Philippines'),
      ('PK', 'PAK', '586', 'Pakistan'),
      ('PL', 'POL', '616', 'Poland'),
      ('PM', 'SPM', '666', 'Saint Pierre and Miquelon'),
      ('PN', 'PCN', '612', 'Pitcairn'),
      ('PR', 'PRI', '630', 'Puerto Rico'),
      ('PS', 'PSE', '275', 'State of Palestine'),
      ('PT', 'PRT', '620', 'Portugal'),
      ('PW', 'PLW', '585', 'Palau'),
      ('PY', 'PRY', '600', 'Paraguay'),
      ('QA', 'QAT', '634', 'Qatar'),
      ('RE', 'REU', '638', 'Réunion'),
      ('RO', 'ROU', '642', 'Romania'),
      ('RS', 'SRB', '688', 'Serbia'),
      ('RU', 'RUS', '643', 'Russian Federation'),
      ('RW', 'RWA', '646', 'Rwanda'),
      ('SA', 'SAU', '682', 'Saudi Arabia'),
      ('SB', 'SLB', '090', 'Solomon Islands'),
      ('SC', 'SYC', '690', 'Seychelles'),
      ('SD', 'SDN', '729', 'Sudan'),
      ('SE', 'SWE', '752', 'Sweden'),
      ('SG', 'SGP', '702', 'Singapore'),
      ('SH', 'SHN', '654', 'Saint Helena'),
      ('SI', 'SVN', '705', 'Slovenia'),
      ('SJ', 'SJM', '744', 'Svalbard and Jan Mayen Islands'),
      ('SK', 'SVK', '703', 'Slovakia'),
      ('SL', 'SLE', '694', 'Sierra Leone'),
      ('SM', 'SMR', '674', 'San Marino'),
      ('SN', 'SEN', '686', 'Senegal'),
      ('SO', 'SOM', '706', 'Somalia'),
      ('SR', 'SUR', '740', 'Suriname'),
      ('SS', 'SSD', '728', 'South Sudan'),
      ('ST', 'STP', '678', 'Sao Tome and Principe'),
      ('SV', 'SLV', '222', 'El Salvador'),
      ('SX', 'SXM', '534', 'Sint Maarten (Dutch part)'),
      ('SY', 'SYR', '760', 'Syrian Arab Republic'),
      ('SZ', 'SWZ', '748', 'Eswatini'),
      ('TC', 'TCA', '796', 'Turks and Caicos Islands'),
      ('TD', 'TCD', '148', 'Chad'),
      ('TF', 'ATF', '260', 'French Southern Territories'),
      ('TG', 'TGO', '768', 'Togo'),
      ('TH', 'THA', '764', 'Thailand'),
      ('TJ', 'TJK', '762', 'Tajikistan'),
      ('TK', 'TKL', '772', 'Tokelau'),
      ('TL', 'TLS', '626', 'Timor-Leste'),
      ('TM', 'TKM', '795', 'Turkmenistan'),
      ('TN', 'TUN', '788', 'Tunisia'),
      ('TO', 'TON', '776', 'Tonga'),
      ('TR', 'TUR', '792', 'Türkiye'),
      ('TT', 'TTO', '780', 'Trinidad and Tobago'),
      ('TV', 'TUV', '798', 'Tuvalu'),
      ('TZ', 'TZA', '834', 'United Republic of Tanzania'),
      ('UA', 'UKR', '804', 'Ukraine'),
      ('UG', 'UGA', '800', 'Uganda'),
      ('UM', 'UMI', '581', 'United States Minor Outlying Islands'),
      ('US', 'USA', '840', 'United States of America'),
      ('UY', 'URY', '858', 'Uruguay'),
      ('UZ', 'UZB', '860', 'Uzbekistan'),
      ('VA', 'VAT', '336', 'Holy See'),
      ('VC', 'VCT', '670', 'Saint Vincent and the Grenadines'),
      ('VE', 'VEN', '862', 'Venezuela (Bolivarian Republic of)'),
      ('VG', 'VGB', '092', 'British Virgin Islands'),
      ('VI', 'VIR', '850', 'United States Virgin Islands'),
      ('VN', 'VNM', '704', 'Viet Nam'),
      ('VU', 'VUT', '548', 'Vanuatu'),
      ('WF', 'WLF', '876', 'Wallis and Futuna Islands'),
      ('WS', 'WSM', '882', 'Samoa'),
      ('YE', 'YEM', '887', 'Yemen'),
      ('YT', 'MYT', '175', 'Mayotte'),
      ('ZA', 'ZAF', '710', 'South Africa'),
      ('ZM', 'ZMB', '894', 'Zambia'),
      ('ZW', 'ZWE', '716', 'Zimbabwe')
    ) AS values_to_seed(alpha2_code, alpha3_code, numeric_code, name)
  LOOP
    SELECT alpha3_code, numeric_code, name INTO existing
    FROM app.countries WHERE alpha2_code = seed.alpha2_code;
    IF FOUND THEN
      IF ROW(existing.alpha3_code, existing.numeric_code, existing.name)
         IS DISTINCT FROM ROW(seed.alpha3_code, seed.numeric_code, seed.name) THEN
        RAISE EXCEPTION 'Country seed conflict for %', seed.alpha2_code;
      END IF;
    ELSE
      INSERT INTO app.countries (alpha2_code, alpha3_code, numeric_code, name)
      VALUES (seed.alpha2_code, seed.alpha3_code, seed.numeric_code, seed.name);
    END IF;
  END LOOP;
END
$$;

DO $$
DECLARE
  seed record;
  existing record;
BEGIN
  FOR seed IN
    SELECT * FROM (VALUES
      ('AED', '784', 2, 'UAE Dirham'),
      ('AFN', '971', 2, 'Afghani'),
      ('ALL', '008', 2, 'Lek'),
      ('AMD', '051', 2, 'Armenian Dram'),
      ('AOA', '973', 2, 'Kwanza'),
      ('ARS', '032', 2, 'Argentine Peso'),
      ('AUD', '036', 2, 'Australian Dollar'),
      ('AWG', '533', 2, 'Aruban Florin'),
      ('AZN', '944', 2, 'Azerbaijan Manat'),
      ('BAM', '977', 2, 'Convertible Mark'),
      ('BBD', '052', 2, 'Barbados Dollar'),
      ('BDT', '050', 2, 'Taka'),
      ('BHD', '048', 3, 'Bahraini Dinar'),
      ('BIF', '108', 0, 'Burundi Franc'),
      ('BMD', '060', 2, 'Bermudian Dollar'),
      ('BND', '096', 2, 'Brunei Dollar'),
      ('BOB', '068', 2, 'Boliviano'),
      ('BRL', '986', 2, 'Brazilian Real'),
      ('BSD', '044', 2, 'Bahamian Dollar'),
      ('BTN', '064', 2, 'Ngultrum'),
      ('BWP', '072', 2, 'Pula'),
      ('BYN', '933', 2, 'Belarusian Ruble'),
      ('BZD', '084', 2, 'Belize Dollar'),
      ('CAD', '124', 2, 'Canadian Dollar'),
      ('CDF', '976', 2, 'Congolese Franc'),
      ('CHF', '756', 2, 'Swiss Franc'),
      ('CLP', '152', 0, 'Chilean Peso'),
      ('CNY', '156', 2, 'Yuan Renminbi'),
      ('COP', '170', 2, 'Colombian Peso'),
      ('CRC', '188', 2, 'Costa Rican Colon'),
      ('CUP', '192', 2, 'Cuban Peso'),
      ('CVE', '132', 2, 'Cabo Verde Escudo'),
      ('CZK', '203', 2, 'Czech Koruna'),
      ('DJF', '262', 0, 'Djibouti Franc'),
      ('DKK', '208', 2, 'Danish Krone'),
      ('DOP', '214', 2, 'Dominican Peso'),
      ('DZD', '012', 2, 'Algerian Dinar'),
      ('EGP', '818', 2, 'Egyptian Pound'),
      ('ERN', '232', 2, 'Nakfa'),
      ('ETB', '230', 2, 'Ethiopian Birr'),
      ('EUR', '978', 2, 'Euro'),
      ('FJD', '242', 2, 'Fiji Dollar'),
      ('FKP', '238', 2, 'Falkland Islands Pound'),
      ('GBP', '826', 2, 'Pound Sterling'),
      ('GEL', '981', 2, 'Lari'),
      ('GHS', '936', 2, 'Ghana Cedi'),
      ('GIP', '292', 2, 'Gibraltar Pound'),
      ('GMD', '270', 2, 'Dalasi'),
      ('GNF', '324', 0, 'Guinean Franc'),
      ('GTQ', '320', 2, 'Quetzal'),
      ('GYD', '328', 2, 'Guyana Dollar'),
      ('HKD', '344', 2, 'Hong Kong Dollar'),
      ('HNL', '340', 2, 'Lempira'),
      ('HTG', '332', 2, 'Gourde'),
      ('HUF', '348', 2, 'Forint'),
      ('IDR', '360', 2, 'Rupiah'),
      ('ILS', '376', 2, 'New Israeli Sheqel'),
      ('INR', '356', 2, 'Indian Rupee'),
      ('IQD', '368', 3, 'Iraqi Dinar'),
      ('IRR', '364', 2, 'Iranian Rial'),
      ('ISK', '352', 0, 'Iceland Krona'),
      ('JMD', '388', 2, 'Jamaican Dollar'),
      ('JOD', '400', 3, 'Jordanian Dinar'),
      ('JPY', '392', 0, 'Yen'),
      ('KES', '404', 2, 'Kenyan Shilling'),
      ('KGS', '417', 2, 'Som'),
      ('KHR', '116', 2, 'Riel'),
      ('KMF', '174', 0, 'Comorian Franc '),
      ('KPW', '408', 2, 'North Korean Won'),
      ('KRW', '410', 0, 'Won'),
      ('KWD', '414', 3, 'Kuwaiti Dinar'),
      ('KYD', '136', 2, 'Cayman Islands Dollar'),
      ('KZT', '398', 2, 'Tenge'),
      ('LAK', '418', 2, 'Lao Kip'),
      ('LBP', '422', 2, 'Lebanese Pound'),
      ('LKR', '144', 2, 'Sri Lanka Rupee'),
      ('LRD', '430', 2, 'Liberian Dollar'),
      ('LSL', '426', 2, 'Loti'),
      ('LYD', '434', 3, 'Libyan Dinar'),
      ('MAD', '504', 2, 'Moroccan Dirham'),
      ('MDL', '498', 2, 'Moldovan Leu'),
      ('MGA', '969', 2, 'Malagasy Ariary'),
      ('MKD', '807', 2, 'Denar'),
      ('MMK', '104', 2, 'Kyat'),
      ('MNT', '496', 2, 'Tugrik'),
      ('MOP', '446', 2, 'Pataca'),
      ('MRU', '929', 2, 'Ouguiya'),
      ('MUR', '480', 2, 'Mauritius Rupee'),
      ('MVR', '462', 2, 'Rufiyaa'),
      ('MWK', '454', 2, 'Malawi Kwacha'),
      ('MXN', '484', 2, 'Mexican Peso'),
      ('MYR', '458', 2, 'Malaysian Ringgit'),
      ('MZN', '943', 2, 'Mozambique Metical'),
      ('NAD', '516', 2, 'Namibia Dollar'),
      ('NGN', '566', 2, 'Naira'),
      ('NIO', '558', 2, 'Cordoba Oro'),
      ('NOK', '578', 2, 'Norwegian Krone'),
      ('NPR', '524', 2, 'Nepalese Rupee'),
      ('NZD', '554', 2, 'New Zealand Dollar'),
      ('OMR', '512', 3, 'Rial Omani'),
      ('PAB', '590', 2, 'Balboa'),
      ('PEN', '604', 2, 'Sol'),
      ('PGK', '598', 2, 'Kina'),
      ('PHP', '608', 2, 'Philippine Peso'),
      ('PKR', '586', 2, 'Pakistan Rupee'),
      ('PLN', '985', 2, 'Zloty'),
      ('PYG', '600', 0, 'Guarani'),
      ('QAR', '634', 2, 'Qatari Rial'),
      ('RON', '946', 2, 'Romanian Leu'),
      ('RSD', '941', 2, 'Serbian Dinar'),
      ('RUB', '643', 2, 'Russian Ruble'),
      ('RWF', '646', 0, 'Rwanda Franc'),
      ('SAR', '682', 2, 'Saudi Riyal'),
      ('SBD', '090', 2, 'Solomon Islands Dollar'),
      ('SCR', '690', 2, 'Seychelles Rupee'),
      ('SDG', '938', 2, 'Sudanese Pound'),
      ('SEK', '752', 2, 'Swedish Krona'),
      ('SGD', '702', 2, 'Singapore Dollar'),
      ('SHP', '654', 2, 'Saint Helena Pound'),
      ('SLE', '925', 2, 'Leone'),
      ('SOS', '706', 2, 'Somali Shilling'),
      ('SRD', '968', 2, 'Surinam Dollar'),
      ('SSP', '728', 2, 'South Sudanese Pound'),
      ('STN', '930', 2, 'Dobra'),
      ('SVC', '222', 2, 'El Salvador Colon'),
      ('SYP', '760', 2, 'Syrian Pound'),
      ('SZL', '748', 2, 'Lilangeni'),
      ('THB', '764', 2, 'Baht'),
      ('TJS', '972', 2, 'Somoni'),
      ('TMT', '934', 2, 'Turkmenistan New Manat'),
      ('TND', '788', 3, 'Tunisian Dinar'),
      ('TOP', '776', 2, 'Pa’anga'),
      ('TRY', '949', 2, 'Turkish Lira'),
      ('TTD', '780', 2, 'Trinidad and Tobago Dollar'),
      ('TWD', '901', 2, 'New Taiwan Dollar'),
      ('TZS', '834', 2, 'Tanzanian Shilling'),
      ('UAH', '980', 2, 'Hryvnia'),
      ('UGX', '800', 0, 'Uganda Shilling'),
      ('USD', '840', 2, 'US Dollar'),
      ('UYU', '858', 2, 'Peso Uruguayo'),
      ('UYW', '927', 4, 'Unidad Previsional'),
      ('UZS', '860', 2, 'Uzbekistan Sum'),
      ('VED', '926', 2, 'Bolívar Soberano'),
      ('VES', '928', 2, 'Bolívar Soberano'),
      ('VND', '704', 0, 'Dong'),
      ('VUV', '548', 0, 'Vatu'),
      ('WST', '882', 2, 'Tala'),
      ('XAD', '396', 2, 'Arab Accounting Dinar'),
      ('XAF', '950', 0, 'CFA Franc BEAC'),
      ('XCD', '951', 2, 'East Caribbean Dollar'),
      ('XCG', '532', 2, 'Caribbean Guilder'),
      ('XOF', '952', 0, 'CFA Franc BCEAO'),
      ('XPF', '953', 0, 'CFP Franc'),
      ('YER', '886', 2, 'Yemeni Rial'),
      ('ZAR', '710', 2, 'Rand'),
      ('ZMW', '967', 2, 'Zambian Kwacha'),
      ('ZWG', '924', 2, 'Zimbabwe Gold')
    ) AS values_to_seed(code, numeric_code, minor_unit, name)
  LOOP
    SELECT numeric_code, minor_unit, name INTO existing
    FROM app.currencies WHERE code = seed.code;
    IF FOUND THEN
      IF ROW(existing.numeric_code, existing.minor_unit, existing.name)
         IS DISTINCT FROM ROW(seed.numeric_code, seed.minor_unit, seed.name) THEN
        RAISE EXCEPTION 'Currency seed conflict for %', seed.code;
      END IF;
    ELSE
      INSERT INTO app.currencies (code, numeric_code, minor_unit, name)
      VALUES (seed.code, seed.numeric_code, seed.minor_unit, seed.name);
    END IF;
  END LOOP;
END
$$;

RESET ROLE;
