import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Privacy declarations (ST-308) — see `store/privacy-labels.md`.
///
/// The iOS privacy manifest, the App Privacy / Data Safety answers and the native build must
/// describe the same app. These checks fail when one of them changes without the others.
void main() {
  final manifest = _read('ios/Runner/PrivacyInfo.xcprivacy');
  final mapping = _read('store/privacy-labels.md');

  test('the app manifest is bundled into the Runner target', () {
    final project = _read('ios/Runner.xcodeproj/project.pbxproj');

    expect(project, contains('/* PrivacyInfo.xcprivacy in Resources */,'));
  });

  test('the app manifest declares no tracking', () {
    expect(manifest, matches(RegExp(r'<key>NSPrivacyTracking</key>\s*<false/>')));
    expect(manifest, matches(RegExp(r'<key>NSPrivacyTrackingDomains</key>\s*<array/>')));
    expect(manifest, isNot(contains('NSPrivacyCollectedDataTypePurposeThirdPartyAdvertising')));
    expect(manifest, isNot(contains('NSPrivacyCollectedDataTypePurposeDeveloperAdvertising')));
  });

  test('collected data types match the App Privacy answers', () {
    final declared = _dataTypes(manifest);

    expect(declared, isNotEmpty);
    expect(declared, _dataTypes(mapping), reason: 'update the manifest and the mapping together');
  });

  test("SQLite's required-reason APIs are declared while the app bundles it", () {
    // Neither the sqlite3 native asset nor the sqlite3 pod ships a manifest, so the app declares
    // the stat/fstat/lstat and statfs/fstatfs calls the bundled library makes.
    final lockfile = _read('pubspec.lock');
    expect(RegExp(r'^  sqlite3:', multiLine: true).hasMatch(lockfile), isTrue);

    expect(manifest, contains('NSPrivacyAccessedAPICategoryFileTimestamp'));
    expect(manifest, contains('C617.1'));
    expect(manifest, contains('NSPrivacyAccessedAPICategoryDiskSpace'));
    expect(manifest, contains('E174.1'));
  });

  test('every iOS plugin in the release build has a manifest row', () {
    final dependencies = File('.flutter-plugins-dependencies');
    if (!dependencies.existsSync()) {
      markTestSkipped('.flutter-plugins-dependencies is generated by `flutter pub get`');
      return;
    }
    final plugins = (jsonDecode(dependencies.readAsStringSync()) as Map)['plugins'] as Map;
    final releasePlugins = {
      for (final plugin in (plugins['ios'] as List).cast<Map>())
        if (plugin['dev_dependency'] != true) plugin['name'] as String,
    };
    final documented = {
      for (final match in RegExp(r'^\| `(\w+)` \|', multiLine: true).allMatches(mapping))
        match.group(1)!,
    };

    expect(releasePlugins.difference(documented), isEmpty);
  });

  test('the listings point at the same policy and deletion pages as the app', () {
    final listing = _read('store/listing-metadata.md');

    for (final url in [
      'https://app.studafy.com/privacy',
      'https://app.studafy.com/legal/delete-account',
    ]) {
      expect(listing, contains(url));
      expect(mapping, contains(url));
    }
  });
}

String _read(String path) => File(path).readAsStringSync();

/// `NSPrivacyCollectedDataType<Name>` values, ignoring the dictionary keys that share the prefix.
Set<String> _dataTypes(String source) => {
  for (final match in RegExp(
    r'NSPrivacyCollectedDataType(?!s\b|Linked|Tracking|Purpose)(\w+)',
  ).allMatches(source))
    match.group(1)!,
};
