import { ROLES, type Role } from "./roles";

/**
 * Full permission matrix, `resource:action`. This is the single source of truth for
 * authorization checks across the platform — see docs/adr/0002-fixed-roles-authorization.md.
 * The generated permission-matrix doc (docs/permission-matrix.md) is derived from this file
 * and ROLE_PERMISSIONS below; never hand-duplicate this list elsewhere.
 */
export const PERMISSIONS = {
  USER_CREATE: "user:create",
  USER_READ: "user:read",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_INVITE: "user:invite",
  USER_SUSPEND: "user:suspend",
  USER_IMPERSONATE: "user:impersonate",

  ROLE_READ: "role:read",
  ROLE_ASSIGN: "role:assign",
  ROLE_REVOKE: "role:revoke",

  ORGANIZATION_CREATE: "organization:create",
  ORGANIZATION_READ: "organization:read",
  ORGANIZATION_UPDATE: "organization:update",
  ORGANIZATION_DELETE: "organization:delete",
  ORGANIZATION_MANAGE_SETTINGS: "organization:manageSettings",
  ORGANIZATION_MANAGE_BILLING: "organization:manageBilling",

  COURSE_CREATE: "course:create",
  COURSE_READ: "course:read",
  COURSE_UPDATE: "course:update",
  COURSE_DELETE: "course:delete",
  COURSE_PUBLISH: "course:publish",
  COURSE_ARCHIVE: "course:archive",
  COURSE_DUPLICATE: "course:duplicate",
  COURSE_MANAGE_ENROLLMENT: "course:manageEnrollment",

  LESSON_CREATE: "lesson:create",
  LESSON_READ: "lesson:read",
  LESSON_UPDATE: "lesson:update",
  LESSON_DELETE: "lesson:delete",
  LESSON_PUBLISH: "lesson:publish",
  LESSON_REORDER: "lesson:reorder",

  ENROLLMENT_CREATE: "enrollment:create",
  ENROLLMENT_READ: "enrollment:read",
  ENROLLMENT_UPDATE: "enrollment:update",
  ENROLLMENT_DELETE: "enrollment:delete",
  ENROLLMENT_APPROVE: "enrollment:approve",
  ENROLLMENT_CANCEL: "enrollment:cancel",

  ASSIGNMENT_CREATE: "assignment:create",
  ASSIGNMENT_READ: "assignment:read",
  ASSIGNMENT_UPDATE: "assignment:update",
  ASSIGNMENT_DELETE: "assignment:delete",
  ASSIGNMENT_PUBLISH: "assignment:publish",
  ASSIGNMENT_EXTEND_DEADLINE: "assignment:extendDeadline",

  SUBMISSION_CREATE: "submission:create",
  SUBMISSION_READ: "submission:read",
  SUBMISSION_UPDATE: "submission:update",
  SUBMISSION_DELETE: "submission:delete",
  SUBMISSION_GRADE: "submission:grade",
  SUBMISSION_REQUEST_RESUBMISSION: "submission:requestResubmission",

  GRADE_READ: "grade:read",
  GRADE_UPDATE: "grade:update",
  GRADE_EXPORT: "grade:export",
  GRADE_OVERRIDE: "grade:override",

  DISCUSSION_CREATE: "discussion:create",
  DISCUSSION_READ: "discussion:read",
  DISCUSSION_UPDATE: "discussion:update",
  DISCUSSION_DELETE: "discussion:delete",
  DISCUSSION_MODERATE: "discussion:moderate",
  DISCUSSION_PIN: "discussion:pin",

  NOTIFICATION_READ: "notification:read",
  NOTIFICATION_SEND: "notification:send",
  NOTIFICATION_MANAGE: "notification:manage",
  NOTIFICATION_DELETE: "notification:delete",

  BILLING_READ: "billing:read",
  BILLING_UPDATE: "billing:update",
  BILLING_REFUND: "billing:refund",
  BILLING_VIEW_INVOICES: "billing:viewInvoices",

  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export",
  REPORT_VIEW_FINANCIAL: "report:viewFinancial",

  AUDIT_LOG_READ: "auditLog:read",
  AUDIT_LOG_EXPORT: "auditLog:export",

  API_KEY_CREATE: "apiKey:create",
  API_KEY_READ: "apiKey:read",
  API_KEY_REVOKE: "apiKey:revoke",

  STUDY_GROUP_CREATE: "studyGroup:create",
  STUDY_GROUP_READ: "studyGroup:read",
  STUDY_GROUP_UPDATE: "studyGroup:update",
  STUDY_GROUP_DELETE: "studyGroup:delete",
  STUDY_GROUP_JOIN: "studyGroup:join",
  STUDY_GROUP_MODERATE: "studyGroup:moderate",

  QUIZ_CREATE: "quiz:create",
  QUIZ_READ: "quiz:read",
  QUIZ_UPDATE: "quiz:update",
  QUIZ_DELETE: "quiz:delete",
  QUIZ_PUBLISH: "quiz:publish",
  QUIZ_GRADE: "quiz:grade",

  CERTIFICATE_ISSUE: "certificate:issue",
  CERTIFICATE_READ: "certificate:read",
  CERTIFICATE_REVOKE: "certificate:revoke",

  STUDENT_CREATE: "student:create",
  STUDENT_READ: "student:read",
  STUDENT_UPDATE: "student:update",
  STUDENT_IMPORT: "student:import",

  TEACHER_CREATE: "teacher:create",
  TEACHER_READ: "teacher:read",
  TEACHER_UPDATE: "teacher:update",

  MATERIAL_CREATE: "material:create",
  MATERIAL_READ: "material:read",
  MATERIAL_UPDATE: "material:update",
  MATERIAL_DELETE: "material:delete",
  MATERIAL_MANAGE_AI: "material:manageAi",

  ATTENDANCE_RECORD_CREATE: "attendance:record:create",

  PARENT_LINK: "parent:link",
  PARENT_UNLINK: "parent:unlink",

  DISCIPLINE_INCIDENT_CREATE: "disciplineIncident:create",
  DISCIPLINE_INCIDENT_READ: "disciplineIncident:read",
  DISCIPLINE_INCIDENT_UPDATE: "disciplineIncident:update",
  DISCIPLINE_INCIDENT_RESOLVE: "disciplineIncident:resolve",

  DISCIPLINE_ACTION_CREATE: "disciplineAction:create",
  DISCIPLINE_ACTION_READ: "disciplineAction:read",
  DISCIPLINE_ACTION_UPDATE: "disciplineAction:update",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ORG_ADMIN_PERMISSIONS: readonly Permission[] = ALL_PERMISSIONS.filter(
  (permission) =>
    permission !== PERMISSIONS.USER_IMPERSONATE &&
    permission !== PERMISSIONS.ORGANIZATION_CREATE &&
    permission !== PERMISSIONS.ORGANIZATION_DELETE &&
    permission !== PERMISSIONS.API_KEY_CREATE &&
    permission !== PERMISSIONS.API_KEY_READ &&
    permission !== PERMISSIONS.API_KEY_REVOKE,
);

const INSTRUCTOR_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.COURSE_CREATE,
  PERMISSIONS.COURSE_READ,
  PERMISSIONS.COURSE_UPDATE,
  PERMISSIONS.COURSE_DELETE,
  PERMISSIONS.COURSE_PUBLISH,
  PERMISSIONS.COURSE_ARCHIVE,
  PERMISSIONS.COURSE_DUPLICATE,
  PERMISSIONS.COURSE_MANAGE_ENROLLMENT,
  PERMISSIONS.LESSON_CREATE,
  PERMISSIONS.LESSON_READ,
  PERMISSIONS.LESSON_UPDATE,
  PERMISSIONS.LESSON_DELETE,
  PERMISSIONS.LESSON_PUBLISH,
  PERMISSIONS.LESSON_REORDER,
  PERMISSIONS.ENROLLMENT_READ,
  PERMISSIONS.ENROLLMENT_APPROVE,
  PERMISSIONS.ASSIGNMENT_CREATE,
  PERMISSIONS.ASSIGNMENT_READ,
  PERMISSIONS.ASSIGNMENT_UPDATE,
  PERMISSIONS.ASSIGNMENT_DELETE,
  PERMISSIONS.ASSIGNMENT_PUBLISH,
  PERMISSIONS.ASSIGNMENT_EXTEND_DEADLINE,
  PERMISSIONS.SUBMISSION_READ,
  PERMISSIONS.SUBMISSION_GRADE,
  PERMISSIONS.SUBMISSION_REQUEST_RESUBMISSION,
  PERMISSIONS.GRADE_READ,
  PERMISSIONS.GRADE_UPDATE,
  PERMISSIONS.DISCUSSION_CREATE,
  PERMISSIONS.DISCUSSION_READ,
  PERMISSIONS.DISCUSSION_UPDATE,
  PERMISSIONS.DISCUSSION_DELETE,
  PERMISSIONS.DISCUSSION_MODERATE,
  PERMISSIONS.DISCUSSION_PIN,
  PERMISSIONS.STUDY_GROUP_CREATE,
  PERMISSIONS.STUDY_GROUP_READ,
  PERMISSIONS.STUDY_GROUP_UPDATE,
  PERMISSIONS.STUDY_GROUP_DELETE,
  PERMISSIONS.STUDY_GROUP_JOIN,
  PERMISSIONS.STUDY_GROUP_MODERATE,
  PERMISSIONS.QUIZ_CREATE,
  PERMISSIONS.QUIZ_READ,
  PERMISSIONS.QUIZ_UPDATE,
  PERMISSIONS.QUIZ_DELETE,
  PERMISSIONS.QUIZ_PUBLISH,
  PERMISSIONS.QUIZ_GRADE,
  PERMISSIONS.CERTIFICATE_ISSUE,
  PERMISSIONS.CERTIFICATE_READ,
  PERMISSIONS.NOTIFICATION_READ,
  PERMISSIONS.NOTIFICATION_SEND,
  PERMISSIONS.STUDENT_READ,
  PERMISSIONS.TEACHER_READ,
  PERMISSIONS.MATERIAL_CREATE,
  PERMISSIONS.MATERIAL_READ,
  PERMISSIONS.MATERIAL_UPDATE,
  PERMISSIONS.MATERIAL_DELETE,
  PERMISSIONS.MATERIAL_MANAGE_AI,
  PERMISSIONS.DISCIPLINE_INCIDENT_CREATE,
  PERMISSIONS.DISCIPLINE_INCIDENT_READ,
  PERMISSIONS.ATTENDANCE_RECORD_CREATE,
];

const TEACHING_ASSISTANT_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.COURSE_READ,
  PERMISSIONS.LESSON_READ,
  PERMISSIONS.ENROLLMENT_READ,
  PERMISSIONS.ASSIGNMENT_READ,
  PERMISSIONS.SUBMISSION_READ,
  PERMISSIONS.SUBMISSION_GRADE,
  PERMISSIONS.SUBMISSION_REQUEST_RESUBMISSION,
  PERMISSIONS.GRADE_READ,
  PERMISSIONS.DISCUSSION_READ,
  PERMISSIONS.DISCUSSION_UPDATE,
  PERMISSIONS.DISCUSSION_MODERATE,
  PERMISSIONS.STUDY_GROUP_READ,
  PERMISSIONS.STUDY_GROUP_MODERATE,
  PERMISSIONS.QUIZ_READ,
  PERMISSIONS.QUIZ_GRADE,
  PERMISSIONS.NOTIFICATION_READ,
  PERMISSIONS.STUDENT_READ,
  PERMISSIONS.MATERIAL_READ,
];

const STUDENT_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.COURSE_READ,
  PERMISSIONS.LESSON_READ,
  PERMISSIONS.ASSIGNMENT_READ,
  PERMISSIONS.SUBMISSION_CREATE,
  PERMISSIONS.SUBMISSION_READ,
  PERMISSIONS.SUBMISSION_UPDATE,
  PERMISSIONS.GRADE_READ,
  PERMISSIONS.DISCUSSION_CREATE,
  PERMISSIONS.DISCUSSION_READ,
  PERMISSIONS.DISCUSSION_UPDATE,
  PERMISSIONS.STUDY_GROUP_CREATE,
  PERMISSIONS.STUDY_GROUP_READ,
  PERMISSIONS.STUDY_GROUP_UPDATE,
  PERMISSIONS.STUDY_GROUP_JOIN,
  PERMISSIONS.QUIZ_READ,
  PERMISSIONS.CERTIFICATE_READ,
  PERMISSIONS.NOTIFICATION_READ,
  PERMISSIONS.STUDENT_READ,
  PERMISSIONS.MATERIAL_READ,
];

// A parent reads their own child's coursework and nothing else. The narrowing is done by the
// database, not by this list: app.is_related_to_student -- the same predicate the
// role_scope_visibility policies on app.assignments and app.assignment_submissions already call --
// resolves parent_child_links, so holding assignment:read here grants a parent exactly the
// assignments their child can see, and submission:read exactly their child's hand-ins (ST-104).
//
// Note what a parent does NOT hold: submission:create, submission:update, submission:grade. They
// can read a submission and they cannot touch one.
const PARENT_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.STUDENT_READ,
  PERMISSIONS.ASSIGNMENT_READ,
  PERMISSIONS.SUBMISSION_READ,
  PERMISSIONS.DISCIPLINE_INCIDENT_READ,
];

const GUEST_PERMISSIONS: readonly Permission[] = [PERMISSIONS.COURSE_READ, PERMISSIONS.LESSON_READ];

const FINANCE_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.BILLING_READ,
  PERMISSIONS.BILLING_UPDATE,
  PERMISSIONS.BILLING_VIEW_INVOICES,
  PERMISSIONS.REPORT_READ,
  PERMISSIONS.REPORT_VIEW_FINANCIAL,
  PERMISSIONS.AUDIT_LOG_READ,
  PERMISSIONS.AUDIT_LOG_EXPORT,
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.USER_READ,
  PERMISSIONS.NOTIFICATION_READ,
];

const SUPPORT_AGENT_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.USER_READ,
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.COURSE_READ,
  PERMISSIONS.ENROLLMENT_READ,
  PERMISSIONS.BILLING_READ,
  PERMISSIONS.BILLING_VIEW_INVOICES,
  PERMISSIONS.REPORT_READ,
  PERMISSIONS.AUDIT_LOG_READ,
  PERMISSIONS.NOTIFICATION_READ,
  PERMISSIONS.NOTIFICATION_SEND,
  PERMISSIONS.STUDENT_READ,
  PERMISSIONS.DISCIPLINE_INCIDENT_READ,
];

/**
 * Static role → permission assignment. `SUPER_ADMIN` intentionally holds every permission,
 * which also guarantees every entry in PERMISSIONS is reachable by at least one role
 * (enforced by permissions.test.ts).
 */
export const ROLE_PERMISSIONS: Readonly<Record<Role, readonly Permission[]>> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ORG_ADMIN]: ORG_ADMIN_PERMISSIONS,
  [ROLES.FINANCE]: FINANCE_PERMISSIONS,
  [ROLES.INSTRUCTOR]: INSTRUCTOR_PERMISSIONS,
  [ROLES.TEACHING_ASSISTANT]: TEACHING_ASSISTANT_PERMISSIONS,
  [ROLES.STUDENT]: STUDENT_PERMISSIONS,
  [ROLES.PARENT]: PARENT_PERMISSIONS,
  [ROLES.GUEST]: GUEST_PERMISSIONS,
  [ROLES.SUPPORT_AGENT]: SUPPORT_AGENT_PERMISSIONS,
};
