/**
 * Pure pseudo-locale transform, shared by `generate-pseudo-locale.ts` (the script that regenerates
 * `qps-ploc.json`) and `pseudo-locale.test.ts` (which asserts that file is still in sync with
 * `en.json` — the same "generated by hand, kept in sync by a test" idiom as `@studafy/ui`'s
 * `tokens.css`).
 *
 * Every letter is swapped for an accented lookalike and the string is padded ~35% longer and
 * bracket-wrapped, so a layout that clips or a template that silently drops a string is immediately
 * visible without needing a linguist to read it.
 */
const ACCENT_MAP: Record<string, string> = {
  a: "á",
  b: "ƀ",
  c: "ç",
  d: "đ",
  e: "é",
  f: "ƒ",
  g: "ğ",
  h: "ħ",
  i: "í",
  j: "ĵ",
  k: "ķ",
  l: "ĺ",
  m: "ɱ",
  n: "ñ",
  o: "ó",
  p: "ρ",
  q: "q̃",
  r: "ŕ",
  s: "š",
  t: "ţ",
  u: "ú",
  v: "ṽ",
  w: "ŵ",
  x: "x̃",
  y: "ý",
  z: "ž",
  A: "Á",
  B: "Β",
  C: "Ç",
  D: "Đ",
  E: "É",
  F: "F̃",
  G: "Ğ",
  H: "Ĥ",
  I: "Í",
  J: "Ĵ",
  K: "Ķ",
  L: "Ĺ",
  M: "M̃",
  N: "Ñ",
  O: "Ó",
  P: "Ρ",
  Q: "Q̃",
  R: "Ŕ",
  S: "Š",
  T: "Ţ",
  U: "Ú",
  V: "Ṽ",
  W: "Ŵ",
  X: "X̃",
  Y: "Ý",
  Z: "Ž",
};

// Deliberately nonsense filler, only ever used to inflate string length — never meant to be read.
const PADDING = "ǝɥʇ ʞɔınb uʍoɹq ɟoxʞ";

const INTERPOLATION_TOKEN = /(\{\{[^}]+\}\})/g;

/** Accents every letter outside `{{ interpolation }}` tokens, which must round-trip untouched. */
function accent(segment: string): string {
  return segment.replace(/[a-zA-Z]/g, (ch) => ACCENT_MAP[ch] ?? ch);
}

function pseudoizeString(value: string): string {
  const accented = value
    .split(INTERPOLATION_TOKEN)
    .map((part) => (part.startsWith("{{") ? part : accent(part)))
    .join("");
  const paddingLength = Math.ceil(value.length * 0.35);
  const padding = PADDING.repeat(Math.ceil(paddingLength / PADDING.length) || 1).slice(
    0,
    paddingLength,
  );
  return `[${accented} ${padding}]`;
}

/** Recursively pseudoizes every string leaf of a translation catalog, preserving its shape. */
export function pseudoizeCatalog(node: unknown): unknown {
  if (typeof node === "string") {
    return pseudoizeString(node);
  }
  if (node !== null && typeof node === "object") {
    return Object.fromEntries(
      Object.entries(node as Record<string, unknown>).map(([key, value]) => [
        key,
        pseudoizeCatalog(value),
      ]),
    );
  }
  return node;
}
