import path from "node:path";

import type { OpenAPITSOptions } from "openapi-typescript";

/**
 * Codegen configuration for `@studafy/api-client`.
 *
 * Kept in one reviewed file rather than inlined in the build script so that a change to how the
 * client's types are shaped shows up as a diff of *this* file, not buried in imperative code.
 *
 * The source of truth is the OpenAPI 3.1 document that ST-060 generates from the live Hono routes
 * (`apps/api/openapi.json`). The file is gitignored (see root .gitignore) to avoid merge conflicts;
 * CI regenerates it before client codegen.
 */

/** Absolute path to the OpenAPI 3.1 document emitted by ST-060. */
export const OPENAPI_SPEC_PATH = path.resolve(
  import.meta.dirname,
  "..",
  "..",
  "apps",
  "api",
  "openapi.json",
);

/** Default destination for the generated types (gitignored; regenerated on demand or in CI). */
export const GENERATED_TYPES_PATH = path.resolve(import.meta.dirname, "src", "generated-types.ts");

/**
 * Options handed to `openapi-typescript`.
 *
 * - `alphabetize` keeps member order stable across regenerations, so the drift diff reflects a real
 *   contract change and never a reshuffle.
 * - `immutable` emits `readonly` members: a generated client type is a wire contract, and code that
 *   mutates a decoded response is almost always a bug.
 * - `enum: false` keeps enums as string-literal unions rather than emitting real TS `enum`s, so a
 *   `status` or `code` value flows as a plain union with zero runtime footprint.
 */
export const OPENAPI_TS_OPTIONS: OpenAPITSOptions = {
  alphabetize: true,
  immutable: true,
  enum: false,
};

/**
 * Banner prepended to the generated file. Mirrors the `x-generated-by` marker ST-060 rides into
 * `openapi.json`: the do-not-edit warning lives in the artifact itself, and CI regenerates it.
 */
export const GENERATED_BANNER = `/* eslint-disable -- generated file; formatting and style are owned by the codegen, not lint. */
/**
 * GENERATED by @studafy/api-client's codegen (scripts/build-api-client.ts) from
 * apps/api/openapi.json (ST-060). Do not hand-edit: regenerate with
 * \`bun run --cwd packages/api-client generate\` instead.
 */
`;
