import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { PERMISSIONS, ROLE_PERMISSIONS } from "../src/permissions";
import { ROLES } from "../src/roles";

/**
 * Regenerates docs/permission-matrix.md straight from PERMISSIONS/ROLE_PERMISSIONS so the
 * documentation can never drift from the actual authorization matrix. Run via `bun run
 * docs:generate`. Do not hand-edit the output file.
 */
function buildMarkdown(): string {
  const roles = Object.values(ROLES);
  const permissions = Object.values(PERMISSIONS);

  const header = `| Permission | ${roles.join(" | ")} |`;
  const divider = `| --- | ${roles.map(() => "---").join(" | ")} |`;

  const rows = permissions.map((permission) => {
    const cells = roles.map((role) => {
      // eslint-disable-next-line security/detect-object-injection -- `role` is drawn only from the fixed ROLES enum, never external input
      const rolePermissions = ROLE_PERMISSIONS[role];
      return rolePermissions.includes(permission) ? "✅" : "";
    });
    return `| \`${permission}\` | ${cells.join(" | ")} |`;
  });

  return [
    "<!-- Generated by scripts/generate-permission-matrix.ts. Do not hand-edit. -->",
    "",
    "# Permission matrix",
    "",
    "Source of truth: `src/permissions.ts` (`PERMISSIONS`, `ROLE_PERMISSIONS`). Regenerate with",
    "`bun run docs:generate` after changing either export.",
    "",
    header,
    divider,
    ...rows,
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const outDir = path.join(import.meta.dirname, "..", "docs");
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, "permission-matrix.md"), buildMarkdown());
}

await main();
