/**
 * The OpenAPI document's static half (ST-060) — everything not derived from a route.
 *
 * Shared by app.ts's served /openapi.json and openapi/document.ts's generated artifact, so the
 * document the server describes and the one committed to the repository are built from one source
 * and cannot disagree. openapi/document.test.ts asserts they are identical.
 *
 * It lives apart from buildOpenApiDocument() to break a cycle: app.ts needs this config to serve
 * /openapi.json, and buildOpenApiDocument() needs createApp from app.ts. Keeping the static half
 * dependency-free means both can import it.
 */
export const OPENAPI_DOCUMENT_CONFIG = {
  openapi: "3.1.0",
  info: {
    title: "Studafy API",
    version: "0.0.0",
    description:
      "HTTP API for Studafy.\n\n" +
      "**Errors.** Every failure is an RFC 9457 `application/problem+json` document. Alongside the " +
      "standard members it carries `code`, a stable machine-readable error code, and `request_id`, " +
      "which correlates the failure with server logs and the audit trail. Read `code`, not " +
      "`title` or `detail` — those are prose and may be localized via `Accept-Language`. 5xx " +
      "problems never carry a `detail`; quote the `request_id` instead.\n\n" +
      "**Correlation.** Every response carries an `X-Request-Id` header. It is generated by the " +
      "server and never read from the request.\n\n" +
      "**Authentication.** Nothing here is authenticated yet. The `bearerAuth` scheme is declared " +
      "for the endpoints that will use it, but no operation requires it today, and the API exposes " +
      "no tenant data as a result.",
    license: { name: "UNLICENSED" },
  },
  servers: [
    { url: "http://localhost:3000", description: "Local development" },
    { url: "https://api.staging.studafy.app", description: "Staging" },
    { url: "https://api.studafy.app", description: "Production" },
  ],
  tags: [
    {
      name: "Health",
      description:
        "Liveness and readiness probes. Never authenticated — an orchestrator has no credentials.",
    },
    {
      name: "ERPNext",
      description:
        "Inbound webhook ingestion from ERPNext. Authenticated by an HMAC signature over the raw " +
        "request body, not by a session token.",
    },
  ],
};
