/**
 * The OpenAPI document's static half (ST-060) — everything not derived from a route.
 *
 * Shared by app.ts's served /openapi.json and openapi/document.ts's generated artifact, so the
 * document the server describes and the one committed to the repository are built from one source
 * and cannot disagree. openapi/document.test.ts asserts they are identical.
 *
 * It lives apart from buildOpenApiDocument() to break a cycle: app.ts needs this config to serve
 * /openapi.json, and buildOpenApiDocument() needs createApp from app.ts. Keeping the static half
 * dependency-free means both can import it.
 */
export const OPENAPI_DOCUMENT_CONFIG = {
  openapi: "3.1.0",
  info: {
    title: "Studafy API",
    version: "0.0.0",
    description:
      "HTTP API for Studafy.\n\n" +
      "**Errors.** Every failure is an RFC 9457 `application/problem+json` document. Alongside the " +
      "standard members it carries `code`, a stable machine-readable error code, and `request_id`, " +
      "which correlates the failure with server logs and the audit trail. Read `code`, not " +
      "`title` or `detail` — those are prose and may be localized via `Accept-Language`. 5xx " +
      "problems never carry a `detail`; quote the `request_id` instead.\n\n" +
      "**Correlation.** Every response carries an `X-Request-Id` header. It is generated by the " +
      "server and never read from the request.\n\n" +
      "**Authentication.** Nothing here is authenticated yet. The `bearerAuth` scheme is declared " +
      "for the endpoints that will use it, but no operation requires it today, and the API exposes " +
      "no tenant data as a result.",
    license: { name: "UNLICENSED" },
  },
  servers: [
    { url: "http://localhost:3000", description: "Local development" },
    { url: "https://api.staging.studafy.app", description: "Staging" },
    { url: "https://api.studafy.app", description: "Production" },
  ],
  tags: [
    {
      name: "Auth",
      description:
        "Authentication and authorization endpoints. The JWKS endpoint is public and " +
        "unauthenticated — clients fetch it to verify access tokens.",
    },
    {
      name: "Health",
      description:
        "Liveness and readiness probes. Never authenticated — an orchestrator has no credentials.",
    },
    {
      name: "ERPNext",
      description:
        "Inbound webhook ingestion from ERPNext. Authenticated by an HMAC signature over the raw " +
        "request body, not by a session token.",
    },
    {
      name: "Invitations",
      description:
        "User invitation management. Authenticated. Invitations are bound to an email and role, " +
        "carry a one-time-use token, and emit an event for email dispatch.",
    },
    {
      name: "Admin",
      description:
        "Administrative operations acting on a user other than the caller. Authenticated and " +
        "additionally gated on a permission from the role matrix, so a valid token is necessary " +
        "but not sufficient. Every operation is tenant-scoped: a target in another school is " +
        "indistinguishable from one that does not exist.",
    },
    {
      name: "Schools",
      description:
        "School management endpoints. Public self-registration creates a new school with its " +
        "first administrator; authenticated endpoints manage existing schools.",
    },
    {
      name: "Academics",
      description:
        "Academic year and term lifecycle management. Authenticated and tenant-scoped. " +
        "Includes CRUD operations and the rollover action for year transitions.",
    },
    {
      name: "Users",
      description:
        "User management and administration. Authenticated and tenant-scoped. " +
        "Includes CRUD operations, role assignment, and deactivation with session revocation.",
    },
    {
      name: "Students",
      description:
        "Student profile and guardians management. Authenticated and tenant-scoped. " +
        "Includes CRUD operations for student records with role-based field projection: " +
        "finance-visible roles receive full profiles including admission data.",
    },
    {
      name: "Teachers",
      description:
        "Teacher profile management. Authenticated and tenant-scoped. " +
        "Includes CRUD operations for teacher records and a self-view endpoint.",
    },
    {
      name: "Imports",
      description:
        "Student CSV import management. Authenticated and tenant-scoped. " +
        "Upload a CSV for validation, review errors, and confirm to enqueue async processing.",
    },
    {
      name: "Timetable",
      description:
        "Timetable version and slot management. Authenticated and tenant-scoped. " +
        "Includes version lifecycle (draft → pending → approved), slot CRUD with teacher/room " +
        "conflict detection, and copy-from-previous-term.",
    },
    {
      name: "Attendance",
      description:
        "Attendance session management. Authenticated and tenant-scoped. " +
        "Open sessions for class periods, list history, retrieve details, " +
        "and transition through the draft → open → submitted → locked lifecycle.",
    },
    {
      name: "Assignments",
      description:
        "Class-scoped coursework. Authenticated and tenant-scoped, then scoped again within the " +
        "tenant: teachers manage assignments only for classes they teach, and students read only " +
        "published work for classes they are actively enrolled in. File attachments are served as " +
        "short-lived pre-signed URLs — a raw storage key never appears in a payload.",
    },
    {
      name: "Submissions",
      description:
        "Student hand-ins and teacher grading. Authenticated and tenant-scoped, then scoped again " +
        "within the tenant: a student sees only their own submission, a linked parent only their " +
        "child's, and a teacher every submission for a class they teach. Score, feedback and " +
        "grader identity are withheld from students and parents until the grade is published — " +
        "the submission stays visible, the marks do not.",
    },
  ],
};
