/* eslint-disable -- generated file; formatting and style are owned by the codegen, not lint. */
/**
 * GENERATED by @studafy/api-client's codegen (scripts/build-api-client.ts) from
 * apps/api/openapi.json (ST-060). Do not hand-edit: CI regenerates this file and fails the build if
 * the working tree comes back dirty, so a manual change is reverted and reported as drift. Run
 * `bun run --cwd packages/api-client generate` and commit the result instead.
 */

export interface paths {
    readonly "/.well-known/jwks.json": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * JSON Web Key Set
         * @description Returns the public RSA keys used to verify RS256 access tokens. Clients should cache this response and refresh periodically.
         */
        readonly get: operations["getJsonWebKeySet"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/users/{userId}/devices": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Force a global logout for a user
         * @description Revokes every live token family the named user holds, on every device, and denylists the access tokens they minted. Use for a compromised account. Answers 200 with `revoked: 0` when the user has no live sessions, does not exist, or belongs to another tenant.
         */
        readonly delete: operations["adminRevokeAllDevices"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/admin/users/{userId}/devices/{deviceId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Revoke one of a user's devices
         * @description Terminates every session on the named device and deregisters it, leaving the user's other devices signed in. Use when one device is lost rather than when an account is compromised.
         */
        readonly delete: operations["adminRevokeDevice"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/devices": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List registered devices
         * @description Every device registered to the authenticated user that has not been revoked, with the number of live sessions on each. Distinct from `/api/auth/sessions`, which lists logins rather than the hardware they happened on — one device may carry several sessions.
         */
        readonly get: operations["listDevices"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/devices/{deviceId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Revoke a device entirely
         * @description Terminates every session on the device and deregisters it, so it stops receiving push notifications as well as losing its logins. Answers 200 with `revoked: 0` when the device does not exist or belongs to someone else — the two are indistinguishable by design.
         */
        readonly delete: operations["revokeDevice"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/devices/{deviceId}/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Terminate every session on a device
         * @description Revokes all live sessions bound to the named device, leaving the device registered. Use `DELETE /api/auth/devices/{deviceId}` instead to also deregister the device itself.
         */
        readonly delete: operations["revokeDeviceSessions"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/invitations/{token}/verify": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Verify an invitation token
         * @description Resolves an invitation bearer token without provisioning an account. Valid responses expose only an obfuscated email hint and school name; unusable invitations use standardized problem details.
         */
        readonly get: operations["verifyInvitation"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * End the current session
         * @description Revokes the token family the presented refresh token belongs to and clears the refresh cookie. Always answers 200, whether or not the token was valid, was already revoked, or was absent entirely — reporting otherwise would let a caller probe for live sessions.
         */
        readonly post: operations["logout"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/refresh": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Rotate a refresh token
         * @description Consumes the presented refresh token and issues a replacement pair. The presented token is invalidated unconditionally — a token is valid exactly once. Re-presenting an already-rotated token is treated as theft: the entire token family is revoked and the session ends.
         */
        readonly post: operations["refreshSession"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/sessions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List active sessions
         * @description Every live session for the authenticated user, one entry per session rather than per token — a long-lived session has rotated many times and each rotation left a row behind.
         */
        readonly get: operations["listSessions"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/sessions/{sessionId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Terminate one session
         * @description Revokes the whole token family behind the named session. Answers 200 with `revoked: 0` when the session does not exist or belongs to someone else — the two are indistinguishable by design, so a caller cannot enumerate other users' session ids.
         */
        readonly delete: operations["revokeSession"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/invitations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Create a user invitation
         * @description Issues a new invitation for a given email and role. Returns a one-time-use token that must be delivered to the invitee (e.g. via email). The raw token is never persisted server-side; only its SHA-256 hash is stored. An `invitation.sent` event is emitted into the outbox for downstream email dispatch.
         */
        readonly post: operations["createInvitation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/invitations/{id}/regenerate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Regenerate a pending invitation
         * @description Atomically revokes the current invitation and issues a new one with a fresh token. The old token stops working immediately. The new raw token is included in the response and must be delivered to the invitee. Both `invitation.revoked` and `invitation.sent` events are emitted.
         */
        readonly post: operations["regenerateInvitation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/invitations/{id}/revoke": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Revoke a pending invitation
         * @description Immediately invalidates a pending invitation by setting revoked_at. The old token stops working on the next acceptance attempt. An `invitation.revoked` event is emitted into the outbox.
         */
        readonly post: operations["revokeInvitation"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/erpnext/webhooks": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Ingest an ERPNext document event
         * @description Accepts a signed document event from ERPNext, records it for deduplication, enqueues an outbox event, and projects the document into the finance cache.
         *
         *     Deduplicated on (school_id, event_id): redelivering an event already seen answers 200 without re-processing it, so ERPNext's at-least-once delivery is safe to retry.
         *
         *     An event whose doctype/action pair maps to no known event also answers 200 — it is delivered, understood, and deliberately ignored. Answering an error would make ERPNext retry forever.
         */
        readonly post: operations["ingestErpNextWebhook"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/healthz": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports that the process is alive. Answers unconditionally — it never checks a dependency, because a liveness probe that fails on a downstream outage would have the orchestrator restart a healthy process.
         */
        readonly get: operations["getLiveness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/readyz": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether this instance should receive traffic. Answers 503 while draining so the load balancer stops routing new requests before in-flight ones finish.
         */
        readonly get: operations["getReadiness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AdminRevocationResult: {
            /** @description Access tokens denylisted. */
            readonly denylisted: number;
            /** @description Refresh tokens revoked. */
            readonly revoked: number;
        };
        readonly CreateInvitation: {
            /**
             * Format: email
             * @description Email address to send the invitation to.
             * @example newuser@example.com
             */
            readonly email: string;
            /**
             * @description Number of days until the invitation expires. Defaults to 7. Must be between 1 and 365.
             * @example 7
             */
            readonly expiry_days?: number;
            /**
             * @description Role to assign when the invitation is accepted.
             * @example STUDENT
             * @enum {string}
             */
            readonly role: "ORG_ADMIN" | "INSTRUCTOR" | "TEACHING_ASSISTANT" | "STUDENT" | "GUEST";
        };
        readonly CreateInvitationResponse: {
            readonly invitation: components["schemas"]["Invitation"];
            /**
             * @description One-time-use invitation token (hex-encoded, 256-bit). This is the only time the raw token is returned. Store it securely and pass it to the invitee — it cannot be retrieved later.
             * @example a1b2c3d4e5f6...
             */
            readonly token: string;
        };
        readonly Device: {
            /** @description Live sessions currently bound to this device. */
            readonly active_session_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly id: string;
            /** Format: date-time */
            readonly last_seen: string;
            readonly platform: string;
        };
        readonly DeviceList: {
            readonly devices: readonly components["schemas"]["Device"][];
        };
        readonly ErpNextWebhook: {
            /** @description ERPNext document action, e.g. 'on_submit'. */
            readonly action: string;
            /** @description The ERPNext document. Must carry school_id (or custom_school_id) — the payload is otherwise untenanted and cannot be routed to a tenant. */
            readonly data: {
                readonly [key: string]: unknown;
            };
            /** @description ERPNext DocType, e.g. 'Sales Invoice'. */
            readonly doctype: string;
            /** @description ERPNext's unique id for this delivery. Used to deduplicate redeliveries. */
            readonly event_id: string;
        };
        readonly ErpNextWebhookAccepted: {
            /** @enum {boolean} */
            readonly ok: true;
        };
        readonly HealthOk: {
            /** @enum {string} */
            readonly status: "ok";
        };
        readonly Invitation: {
            /**
             * Format: date-time
             * @description Issuance timestamp (ISO 8601).
             */
            readonly created_at: string;
            /**
             * Format: email
             * @description Invited email address.
             */
            readonly email: string;
            /**
             * Format: date-time
             * @description Expiry timestamp (ISO 8601).
             */
            readonly expires_at: string;
            /**
             * Format: uuid
             * @description Unique invitation identifier.
             */
            readonly id: string;
            /** @description Role to be assigned on acceptance. */
            readonly role: string;
        };
        readonly InvitationVerificationResponse: {
            /**
             * @description Obfuscated normalized invitation email address.
             * @example j***e@example.com
             */
            readonly emailHint: string;
            /** @description Inviting school's display name. */
            readonly schoolName: string;
            /** @enum {string} */
            readonly state: "valid";
        };
        readonly JsonWebKeySet: {
            readonly keys: readonly {
                /** @enum {string} */
                readonly alg: "RS256";
                readonly e: string;
                readonly kid: string;
                readonly kty: string;
                readonly n: string;
                /** @enum {string} */
                readonly use: "sig";
            }[];
        };
        readonly LogoutResult: {
            /** @enum {boolean} */
            readonly ended: true;
        };
        readonly ProblemDetails: {
            /** @enum {string} */
            readonly code: "AUTH_INVALID_CREDENTIALS" | "AUTH_TOKEN_EXPIRED" | "AUTH_TOKEN_INVALID" | "AUTH_SESSION_NOT_FOUND" | "INVITATION_INVALID" | "EXPIRED" | "REVOKED" | "CONSUMED" | "SCHOOL_SUSPENDED" | "OAUTH_STATE_INVALID" | "OAUTH_EMAIL_NOT_VERIFIED" | "OAUTH_PROVIDER_ERROR" | "AUTHZ_FORBIDDEN" | "AUTHZ_ROLE_NOT_FOUND" | "AUTHZ_PERMISSION_NOT_FOUND" | "VALIDATION_FAILED" | "VALIDATION_REQUIRED_FIELD_MISSING" | "RESOURCE_NOT_FOUND" | "RESOURCE_ALREADY_DELETED" | "CONFLICT_DUPLICATE_ENTRY" | "CONFLICT_STATE_MISMATCH" | "CONFLICT_IDEMPOTENCY_KEY_MISMATCH" | "RATE_LIMIT_EXCEEDED" | "INTERNAL_ERROR";
            readonly detail?: string;
            readonly instance?: string;
            /** Format: uuid */
            readonly request_id: string;
            readonly status: number;
            readonly title: string;
            /** @default about:blank */
            readonly type: string;
        };
        readonly ReadyDraining: {
            /** @enum {string} */
            readonly status: "shutting_down";
        };
        readonly ReadyOk: {
            /** @enum {string} */
            readonly status: "ready";
        };
        readonly RefreshRequest: {
            /** @description The current refresh token. Omit for web sessions, which send it automatically as a cookie. */
            readonly refresh_token?: string;
        };
        readonly RegenerateInvitationResponse: {
            readonly invitation: components["schemas"]["Invitation"];
            /**
             * Format: uuid
             * @description ID of the old invitation that was revoked.
             */
            readonly revoked_invitation_id: string;
            /** @description One-time-use invitation token for the new invitation. This is the only time the raw token is returned. */
            readonly token: string;
        };
        readonly RevocationResult: {
            /** @description Access tokens written to the denylist. Never exceeds `revoked`; sessions predating the access-token tracking added in ST-072 have no identifier to deny. */
            readonly denylisted: number;
            /** @description Tokens revoked. */
            readonly revoked: number;
        };
        readonly RevokeInvitationResponse: {
            /**
             * Format: email
             * @description Invited email address.
             */
            readonly email: string;
            /**
             * Format: uuid
             * @description Revoked invitation identifier.
             */
            readonly id: string;
            /**
             * Format: date-time
             * @description Revocation timestamp (ISO 8601).
             */
            readonly revoked_at: string;
            /** @description Role that was assigned. */
            readonly role: string;
        };
        readonly School: {
            /** Format: uuid */
            readonly country_id: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly default_currency_id: string;
            /**
             * Format: uuid
             * @description Primary key. This is the tenant identifier.
             */
            readonly id: string;
            /** @description Display name. */
            readonly name: string;
            /**
             * @description URL-safe unique identifier.
             * @example springfield-high
             */
            readonly slug: string;
            /**
             * @description Lifecycle state of the school tenant.
             * @enum {string}
             */
            readonly status: "pending" | "active" | "suspended" | "archived";
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly Session: {
            /** @enum {string} */
            readonly channel: "web" | "mobile" | "api";
            /** Format: uuid */
            readonly device_id: string | null;
            readonly device_name: string | null;
            /** Format: date-time */
            readonly expires_at: string;
            /** Format: uuid */
            readonly id: string;
            readonly ip_address: string | null;
            /** Format: date-time */
            readonly issued_at: string;
            readonly user_agent: string | null;
        };
        readonly SessionList: {
            readonly sessions: readonly components["schemas"]["Session"][];
        };
        readonly TokenPair: {
            /** @description RS256 JWT. Send as `Authorization: Bearer`. */
            readonly access_token: string;
            /** @description Access-token lifetime in seconds. */
            readonly expires_in: number;
            /** @description The next refresh token. Present only for `mobile` and `api` sessions. Web sessions receive it as an HttpOnly, Secure, SameSite=Strict cookie instead and never see it here. */
            readonly refresh_token?: string;
            /**
             * Format: uuid
             * @description Identifies this session in the session list.
             */
            readonly session_id: string;
            /** @enum {string} */
            readonly token_type: "Bearer";
        };
        readonly User: {
            /** Format: date-time */
            readonly created_at: string;
            /** @description Optional human-readable name. */
            readonly display_name: string | null;
            /**
             * @description Contact address as supplied. Unique per school after normalization.
             * @example student@example.edu
             */
            readonly email: string;
            /**
             * Format: date-time
             * @description Null until the address is verified.
             */
            readonly email_verified_at: string | null;
            /**
             * Format: uuid
             * @description Primary key.
             */
            readonly id: string;
            /**
             * Format: date-time
             * @description Null until first login.
             */
            readonly last_login_at: string | null;
            /**
             * Format: uuid
             * @description Owning school tenant. Immutable — enforced by a database trigger, not policy.
             */
            readonly school_id: string;
            /**
             * @description Lifecycle state of the user within its school.
             * @enum {string}
             */
            readonly status: "invited" | "active" | "suspended" | "archived";
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly getJsonWebKeySet: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The current JSON Web Key Set. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["JsonWebKeySet"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly adminRevokeAllDevices: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly userId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description How much was torn down. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminRevocationResult"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authenticated, but not permitted to perform this operation. */
            readonly 403: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly adminRevokeDevice: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly deviceId: string;
                readonly userId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description How much was torn down. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminRevocationResult"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authenticated, but not permitted to perform this operation. */
            readonly 403: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly listDevices: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The caller's registered devices. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DeviceList"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly revokeDevice: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly deviceId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description How many tokens were revoked. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RevocationResult"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly revokeDeviceSessions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly deviceId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description How many tokens were revoked. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RevocationResult"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly verifyInvitation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description One-time invitation bearer token (64 lowercase hexadecimal characters). */
                readonly token: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The invitation is active and can proceed to onboarding. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["InvitationVerificationResponse"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request conflicts with the current state of the resource. */
            readonly 409: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly logout: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        readonly responses: {
            /** @description The session is ended. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LogoutResult"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly refreshSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        readonly responses: {
            /** @description A new token pair. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly listSessions: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The caller's active sessions. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SessionList"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly revokeSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly sessionId: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description How many tokens were revoked. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RevocationResult"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly createInvitation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateInvitation"];
            };
        };
        readonly responses: {
            /** @description Invitation created. The raw token is included in this response only. */
            readonly 201: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CreateInvitationResponse"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authenticated, but not permitted to perform this operation. */
            readonly 403: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The request conflicts with the current state of the resource. */
            readonly 409: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly regenerateInvitation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Invitation identifier. */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Old invitation revoked, new invitation created. The raw token is included in this response only. */
            readonly 201: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RegenerateInvitationResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authenticated, but not permitted to perform this operation. */
            readonly 403: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such resource, or it is not visible to this tenant. */
            readonly 404: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly revokeInvitation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Invitation identifier. */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Invitation revoked. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RevokeInvitationResponse"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authenticated, but not permitted to perform this operation. */
            readonly 403: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such resource, or it is not visible to this tenant. */
            readonly 404: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Rate limit exceeded. Back off and retry. */
            readonly 429: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly ingestErpNextWebhook: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Hex-encoded HMAC-SHA256 of the raw request body, keyed with the shared webhook secret. Verified before the body is parsed; compared with a timing-safe equality. */
                readonly "x-erpnext-signature": string;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ErpNextWebhook"];
            };
        };
        readonly responses: {
            /** @description Event accepted, deduplicated, or knowingly ignored. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ErpNextWebhookAccepted"];
                };
            };
            /** @description The request was malformed or failed schema validation. */
            readonly 400: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Authentication is missing or invalid. */
            readonly 401: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly getLiveness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The process is alive. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthOk"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    readonly getReadiness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Ready for traffic. */
            readonly 200: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ReadyOk"];
                };
            };
            /** @description Unexpected server error. The body carries no detail; correlate via request_id. */
            readonly 500: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Draining. The load balancer should stop routing here. */
            readonly 503: {
                headers: {
                    /** @description Server-generated correlation id, present on every response. Never read from the request. Matches the `request_id` member of a problem+json body and the request_id in server logs. */
                    readonly "X-Request-Id": string;
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ReadyDraining"];
                };
            };
        };
    };
}
