/**
 * The app's i18next instance. Resources are bundled at build time (no `i18next-http-backend`) so
 * the first render already has translations — there is no loading flash and no `Suspense` boundary
 * needed around translated text. `initImmediate: false` keeps `init()` synchronous under Bun's test
 * runner too, so tests never need to await it.
 *
 * The pseudo-locale (`qps-ploc`, generated by `locales/generate-pseudo-locale.ts` — see
 * `locales/pseudo-locale.ts`) is registered only in development builds. It is deliberately outside
 * the `Locale` union: it's a stress-test of the English strings' length, not a real locale a user
 * picks, so it never touches `dir`, the locale switcher, or persistence — see the i18n contribution
 * guide for how QA activates it.
 */
import i18next from "i18next";
import { initReactI18next } from "react-i18next";

import { DEFAULT_LOCALE } from "./config";
import ar from "./locales/ar.json";
import en from "./locales/en.json";
import pseudo from "./locales/qps-ploc.json";
import { localeStore } from "./store";

const resources: Record<string, { translation: Record<string, unknown> }> = {
  en: { translation: en },
  ar: { translation: ar },
  ...(import.meta.env.DEV ? { "qps-ploc": { translation: pseudo } } : {}),
};

void i18next.use(initReactI18next).init({
  resources,
  lng: localeStore.getLocale(),
  fallbackLng: DEFAULT_LOCALE,
  interpolation: { escapeValue: false }, // React already escapes interpolated values.
  initImmediate: false,
  returnEmptyString: false,
});

declare global {
  interface Window {
    __STUDAFY_I18N__?: typeof i18next;
  }
}

if (import.meta.env.DEV && typeof window !== "undefined") {
  // Dev-only QA hook: `window.__STUDAFY_I18N__.changeLanguage("qps-ploc")` from the console. Not a
  // production API and not covered by SemVer — see the i18n contribution guide.
  window.__STUDAFY_I18N__ = i18next;
}

export { i18next };
